# Generated by Django 3.1 on 2022-06-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESMaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
