# Generated by Django 3.1 on 2022-06-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESMaker', '0002_question_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
