# Generated by Django 3.1 on 2022-06-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESMaker', '0003_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='company_name',
        ),
    ]
