# Generated by Django 3.1 on 2022-06-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESMaker', '0005_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='es',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='es',
            name='userid',
        ),
        migrations.AddField(
            model_name='es',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
