# Generated by Django 3.1 on 2022-06-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESMaker', '0006_auto_20220618_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='es',
            old_name='question_id',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='es',
            old_name='company_name',
            new_name='question',
        ),
        migrations.AddField(
            model_name='es',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='es',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
